# Generated by Django 4.2.30 on 2026-08-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='role',
            field=models.CharField(choices=[('seller', 'Vendedor'), ('recharge', 'Caixa de recarga'), ('checkin', 'Check-in')], max_length=20),
        ),
    ]
