# Generated by Django 4.2.30 on 2026-07-10 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Festa Junina da Igreja', max_length=255)),
                ('slug', models.SlugField(default='festa-junina', unique=True)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sales_end_at', models.DateTimeField(blank=True, null=True)),
                ('capacity_total', models.PositiveIntegerField(default=0, help_text='0 significa sem limite')),
                ('no_refund_policy', models.TextField(default='Nao ha reembolso.')),
                ('is_sales_paused', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracao do Evento',
                'verbose_name_plural': 'Configuracoes do Evento',
            },
        ),
    ]
