# Generated by Django 4.2.30 on 2026-07-12 00:05

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_document',
            field=models.CharField(default='', max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(default=apps.orders.models.generate_order_code, editable=False, max_length=10, unique=True),
        ),
    ]
