# Generated by Django 4.2.30 on 2026-08-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_buyer_document_alter_order_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pix', 'PIX'), ('credit_card', 'Cartao'), ('courtesy', 'Cortesia')], max_length=20),
        ),
    ]
