# Generated by Django 4.2.30 on 2026-08-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_child_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Criado'), ('activated', 'Ativado'), ('edited', 'Editado'), ('transferred', 'Transferido'), ('reissued', 'Reemitido'), ('checked_in', 'Check-in'), ('resent', 'Reenviado'), ('checkin_undone', 'Check-in desfeito')], max_length=20),
        ),
    ]
